"""The deployment stack must forward every setting it documents.

Nothing else catches a gap here. The app boots fine with a setting missing —
it falls back to the default in ``config.py`` — so the failure only shows up
in production, as a feature that is silently inert:

* ``MEMSHIP_SECRET_KEY`` unset means the app mints its own key under
  ``storage/``, so a database dump restored onto a rebuilt host cannot decrypt
  a single stored SSO or payment credential;
* ``BACKEND_PUBLIC_URL`` left at its ``localhost`` default builds an SSO
  callback the provider rejects, and a Redsys ``Ds_Merchant_MerchantURL`` the
  gateway cannot reach — so cards are charged and the receipts never settle.

Both were written into ``.env`` by ``scripts/install.sh`` and then dropped on
the way to the container. These tests tie the three files together: a setting
documented in ``.env.example`` or generated by the installer has to arrive.
"""

import re
from pathlib import Path

import pytest
import yaml

from app.core.config import Settings

REPO_ROOT = Path(__file__).resolve().parents[3]
COMPOSE_FILE = REPO_ROOT / "docker-compose.yml"
ENV_EXAMPLE = REPO_ROOT / ".env.example"
INSTALL_SCRIPT = REPO_ROOT / "scripts" / "install.sh"

# Variables compose consumes itself — image tags, host paths, published ports,
# the uid the containers run as, the Postgres password it feeds the db service.
# These are deployment knobs, not application settings, and the backend has no
# business seeing them.
COMPOSE_LEVEL_VARS = frozenset(
    {
        "API_BIND",
        "API_IMAGE",
        "API_PORT",
        "DB_BIND",
        "DB_PASSWORD",
        "DB_PORT",
        "FRONTEND_IMAGE",
        "HOST_GID",
        "HOST_UID",
        "HTTPS_PORT",
        "HTTP_PORT",
        "IMAGE_TAG",
        "MEMSHIP_DATA_ROOT",
        "SITE_ADDRESS",
    }
)

SETTING_NAMES = frozenset(Settings.model_fields)


def _assignments(text: str) -> set[str]:
    """Uncommented ``NAME=`` assignments, one per line."""
    return set(re.findall(r"^([A-Z][A-Z0-9_]*)=", text, re.MULTILINE))


@pytest.fixture(scope="module")
def compose() -> dict:
    return yaml.safe_load(COMPOSE_FILE.read_text(encoding="utf-8"))


@pytest.fixture(scope="module")
def forwarded(compose) -> set[str]:
    """The names the shared backend anchor passes to the containers."""
    return set(compose["x-backend-env"])


@pytest.fixture(scope="module")
def documented() -> set[str]:
    return _assignments(ENV_EXAMPLE.read_text(encoding="utf-8"))


@pytest.fixture(scope="module")
def generated() -> set[str]:
    """The names ``install.sh`` writes into the .env it generates."""
    text = INSTALL_SCRIPT.read_text(encoding="utf-8")
    heredoc = re.search(r'cat > "\$ENV_FILE" <<EOF\n(.*?)\n^EOF$', text, re.S | re.M)
    assert heredoc, "install.sh no longer writes .env from a `cat > $ENV_FILE <<EOF` heredoc"
    return _assignments(heredoc.group(1))


class TestEveryDocumentedSettingReachesTheContainer:
    def test_env_example_settings_are_all_forwarded(self, documented, forwarded):
        missing = {n for n in documented if n in SETTING_NAMES} - forwarded
        assert not missing, (
            f"documented in .env.example but never passed to the backend: {sorted(missing)}"
        )

    def test_env_example_holds_nothing_unaccounted_for(self, documented):
        """A new name in .env.example is either an app setting or a compose knob.

        If it is neither, it is a typo — and a typo'd setting is exactly the
        silent no-op this module exists to catch.
        """
        stray = documented - SETTING_NAMES - COMPOSE_LEVEL_VARS
        assert not stray, (
            f".env.example documents names that are neither a Settings field nor a "
            f"compose-level variable: {sorted(stray)}"
        )

    def test_installer_generated_settings_are_all_forwarded(self, generated, forwarded):
        """install.sh generating a secret that never arrives is worse than not
        generating it — it reads as configured while the app ignores it."""
        missing = {n for n in generated if n in SETTING_NAMES} - forwarded
        assert not missing, (
            f"written to .env by install.sh but never passed to the backend: {sorted(missing)}"
        )

    def test_the_anchor_forwards_nothing_the_app_does_not_read(self, forwarded):
        unread = forwarded - SETTING_NAMES
        assert not unread, (
            f"passed to the backend but not a Settings field — renamed or dead: {sorted(unread)}"
        )


class TestTheSettingsWhoseDefaultsFailSilently:
    def test_the_secrets_key_is_forwarded(self, forwarded):
        assert "MEMSHIP_SECRET_KEY" in forwarded

    def test_the_public_backend_url_is_forwarded(self, forwarded, compose):
        assert "BACKEND_PUBLIC_URL" in forwarded

    def test_the_public_backend_url_defaults_to_the_site_not_the_dev_api_port(self, compose):
        """``config.py`` defaults it to ``http://localhost:8003``, the port the
        API is published on in development. Caddy serves the API and the
        frontend on one host, so the compose default has to be the site origin
        — falling through to the config default points Redsys at a dev port."""
        anchor = compose["x-backend-env"]
        default = anchor["BACKEND_PUBLIC_URL"].split(":-", 1)[1].rstrip("}")

        assert default == anchor["FRONTEND_URL"].split(":-", 1)[1].rstrip("}")

    def test_both_mail_transports_are_configurable(self, forwarded):
        """Resend is the documented preferred transport; it was impossible to
        configure by environment at all."""
        assert {"RESEND_API_KEY", "RESEND_FROM_EMAIL"} <= forwarded

    def test_sso_is_configurable_without_the_settings_screen(self, forwarded):
        assert {"GOOGLE_CLIENT_ID", "GOOGLE_CLIENT_SECRET"} <= forwarded
        assert {
            "APPLE_CLIENT_ID",
            "APPLE_TEAM_ID",
            "APPLE_KEY_ID",
            "APPLE_PRIVATE_KEY",
        } <= forwarded


class TestTheWorkersSeeTheSameSettingsAsTheApi:
    """The anchor exists so a setting cannot be added to the API and forgotten
    on the workers — where the billing run and every outbound email execute."""

    @pytest.mark.parametrize("service", ["celery-worker", "celery-beat"])
    def test_a_worker_differs_from_the_api_only_in_run_migrations(self, compose, service):
        api = compose["services"]["api"]["environment"]
        worker = compose["services"][service]["environment"]

        assert set(api) == set(worker)
        assert api["RUN_MIGRATIONS"] == 1
        assert worker["RUN_MIGRATIONS"] == 0