"""add_stripe_columns_to_receipts_and_persons

Revision ID: 31484ce4ff84
Revises: 6c818ec5bfc1
Create Date: 2026-04-16 17:06:08.221483
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31484ce4ff84'
down_revision: Union[str, None] = '6c818ec5bfc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('persons', sa.Column('stripe_customer_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_persons_stripe_customer_id'), 'persons', ['stripe_customer_id'], unique=True)
    op.add_column('receipts', sa.Column('stripe_checkout_session_id', sa.String(length=255), nullable=True))
    op.add_column('receipts', sa.Column('stripe_payment_intent_id', sa.String(length=255), nullable=True))
    op.add_column('receipts', sa.Column('refund_amount', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('receipts', sa.Column('refund_date', sa.Date(), nullable=True))
    op.add_column('receipts', sa.Column('refund_reason', sa.String(length=255), nullable=True))

    # Update payment_method CHECK constraint to include stripe_checkout
    op.drop_constraint('valid_payment_method', 'receipts', type_='check')
    op.create_check_constraint(
        'valid_payment_method',
        'receipts',
        "payment_method IN ('cash', 'bank_transfer', 'card', 'direct_debit', 'stripe_checkout') OR payment_method IS NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('receipts', 'refund_reason')
    op.drop_column('receipts', 'refund_date')
    op.drop_column('receipts', 'refund_amount')
    op.drop_column('receipts', 'stripe_payment_intent_id')
    op.drop_column('receipts', 'stripe_checkout_session_id')
    op.drop_index(op.f('ix_persons_stripe_customer_id'), table_name='persons')
    op.drop_column('persons', 'stripe_customer_id')

    # Restore original payment_method CHECK constraint
    op.drop_constraint('valid_payment_method', 'receipts', type_='check')
    op.create_check_constraint(
        'valid_payment_method',
        'receipts',
        "payment_method IN ('cash', 'bank_transfer', 'card', 'direct_debit') OR payment_method IS NULL",
    )
    # ### end Alembic commands ###
