"""add_concepts_receipts_and_payment_settings

Revision ID: 353eb0c7affe
Revises: e5f6a7b8c9d0
Create Date: 2026-03-26 02:10:00.396931
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '353eb0c7affe'
down_revision: Union[str, None] = 'e5f6a7b8c9d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('concepts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('concept_type', sa.String(length=20), nullable=False),
    sa.Column('default_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('vat_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('default_discount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('default_discount_type', sa.String(length=20), nullable=True),
    sa.Column('accounting_code', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("concept_type IN ('membership', 'activity', 'manual', 'service')", name='valid_concept_type'),
    sa.CheckConstraint("default_discount_type IN ('percentage', 'fixed') OR default_discount_type IS NULL", name='valid_discount_type'),
    sa.CheckConstraint('default_amount >= 0', name='concept_amount_non_negative'),
    sa.CheckConstraint('vat_rate >= 0 AND vat_rate <= 100', name='concept_vat_rate_range'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_concepts_id'), 'concepts', ['id'], unique=False)
    op.create_table('receipts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('receipt_number', sa.String(length=50), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('concept_id', sa.Integer(), nullable=True),
    sa.Column('registration_id', sa.Integer(), nullable=True),
    sa.Column('remittance_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('origin', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('base_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('vat_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('vat_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('discount_type', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('payment_method', sa.String(length=20), nullable=True),
    sa.Column('emission_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.Column('return_date', sa.Date(), nullable=True),
    sa.Column('return_reason', sa.String(length=255), nullable=True),
    sa.Column('is_batchable', sa.Boolean(), nullable=False),
    sa.Column('transaction_id', sa.String(length=255), nullable=True),
    sa.Column('billing_period_start', sa.Date(), nullable=True),
    sa.Column('billing_period_end', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("discount_type IN ('percentage', 'fixed') OR discount_type IS NULL", name='valid_receipt_discount_type'),
    sa.CheckConstraint("origin IN ('membership', 'activity', 'manual', 'service')", name='valid_receipt_origin'),
    sa.CheckConstraint("payment_method IN ('cash', 'bank_transfer', 'card', 'direct_debit') OR payment_method IS NULL", name='valid_payment_method'),
    sa.CheckConstraint("status IN ('new', 'pending', 'emitted', 'paid', 'returned', 'cancelled', 'overdue')", name='valid_receipt_status'),
    sa.CheckConstraint('base_amount >= 0', name='receipt_base_non_negative'),
    sa.CheckConstraint('total_amount >= 0', name='receipt_total_non_negative'),
    sa.CheckConstraint('vat_rate >= 0 AND vat_rate <= 100', name='receipt_vat_range'),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['registration_id'], ['registrations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('receipt_number')
    )
    op.create_index('ix_receipts_emission_date', 'receipts', ['emission_date'], unique=False)
    op.create_index(op.f('ix_receipts_id'), 'receipts', ['id'], unique=False)
    op.create_index('ix_receipts_member_id', 'receipts', ['member_id'], unique=False)
    op.create_index('ix_receipts_origin', 'receipts', ['origin'], unique=False)
    op.create_index('ix_receipts_status', 'receipts', ['status'], unique=False)
    op.add_column('organization_settings', sa.Column('invoice_annual_reset', sa.Boolean(), nullable=True))
    op.add_column('organization_settings', sa.Column('default_vat_rate', sa.Numeric(precision=5, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organization_settings', 'default_vat_rate')
    op.drop_column('organization_settings', 'invoice_annual_reset')
    op.drop_index('ix_receipts_status', table_name='receipts')
    op.drop_index('ix_receipts_origin', table_name='receipts')
    op.drop_index('ix_receipts_member_id', table_name='receipts')
    op.drop_index(op.f('ix_receipts_id'), table_name='receipts')
    op.drop_index('ix_receipts_emission_date', table_name='receipts')
    op.drop_table('receipts')
    op.drop_index(op.f('ix_concepts_id'), table_name='concepts')
    op.drop_table('concepts')
    # ### end Alembic commands ###
