"""add_activities_modalities_prices_tables

Revision ID: 7eb6d537f358
Revises: f993a3100855
Create Date: 2026-03-18 14:47:44.508157
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7eb6d537f358'
down_revision: Union[str, None] = 'f993a3100855'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('short_description', sa.String(length=500), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('location_details', sa.Text(), nullable=True),
    sa.Column('location_url', sa.String(length=500), nullable=True),
    sa.Column('registration_starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('registration_ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('min_participants', sa.Integer(), nullable=True),
    sa.Column('max_participants', sa.Integer(), nullable=False),
    sa.Column('current_participants', sa.Integer(), nullable=True),
    sa.Column('waitlist_count', sa.Integer(), nullable=True),
    sa.Column('min_age', sa.Integer(), nullable=True),
    sa.Column('max_age', sa.Integer(), nullable=True),
    sa.Column('allowed_membership_types', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('registration_fields_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('requirements', sa.Text(), nullable=True),
    sa.Column('what_to_bring', sa.Text(), nullable=True),
    sa.Column('cancellation_policy', sa.Text(), nullable=True),
    sa.Column('allow_self_cancellation', sa.Boolean(), nullable=True),
    sa.Column('self_cancellation_deadline_hours', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.CheckConstraint("slug ~ '^[a-z0-9-]+$'", name='activity_slug_format'),
    sa.CheckConstraint("status IN ('draft', 'published', 'cancelled', 'completed', 'archived')", name='valid_status'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('idx_activities_is_active', 'activities', ['is_active'], unique=False)
    op.create_index('idx_activities_is_featured', 'activities', ['is_featured'], unique=False)
    op.create_index('idx_activities_slug', 'activities', ['slug'], unique=False)
    op.create_index('idx_activities_starts_at', 'activities', ['starts_at'], unique=False)
    op.create_index('idx_activities_status', 'activities', ['status'], unique=False)
    op.create_table('activity_modalities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('max_participants', sa.Integer(), nullable=True),
    sa.Column('current_participants', sa.Integer(), nullable=True),
    sa.Column('registration_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('activity_id', 'name', name='uq_activity_modality_name')
    )
    op.create_index('idx_activity_modalities_activity_id', 'activity_modalities', ['activity_id'], unique=False)
    op.create_table('activity_prices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('modality_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('is_optional', sa.Boolean(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('is_visible', sa.Boolean(), nullable=True),
    sa.Column('max_registrations', sa.Integer(), nullable=True),
    sa.Column('current_registrations', sa.Integer(), nullable=True),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('amount >= 0', name='activity_price_amount_non_negative'),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['modality_id'], ['activity_modalities.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_activity_prices_activity_id', 'activity_prices', ['activity_id'], unique=False)
    op.create_index('idx_activity_prices_modality_id', 'activity_prices', ['modality_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_activity_prices_modality_id', table_name='activity_prices')
    op.drop_index('idx_activity_prices_activity_id', table_name='activity_prices')
    op.drop_table('activity_prices')
    op.drop_index('idx_activity_modalities_activity_id', table_name='activity_modalities')
    op.drop_table('activity_modalities')
    op.drop_index('idx_activities_status', table_name='activities')
    op.drop_index('idx_activities_starts_at', table_name='activities')
    op.drop_index('idx_activities_slug', table_name='activities')
    op.drop_index('idx_activities_is_featured', table_name='activities')
    op.drop_index('idx_activities_is_active', table_name='activities')
    op.drop_table('activities')
    # ### end Alembic commands ###
