"""add_sepa_mandates_remittances_providers

Revision ID: be824d96ca35
Revises: 353eb0c7affe
Create Date: 2026-04-08 13:06:59.445568
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'be824d96ca35'
down_revision: Union[str, None] = '353eb0c7affe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_providers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_type', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("status IN ('active', 'test', 'disabled')", name='valid_provider_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_providers_id'), 'payment_providers', ['id'], unique=False)
    op.create_table('remittances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('remittance_number', sa.String(length=50), nullable=False),
    sa.Column('remittance_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('emission_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('receipt_count', sa.Integer(), nullable=False),
    sa.Column('sepa_file_path', sa.String(length=500), nullable=True),
    sa.Column('creditor_name', sa.String(length=255), nullable=False),
    sa.Column('creditor_iban', sa.String(length=34), nullable=False),
    sa.Column('creditor_bic', sa.String(length=11), nullable=True),
    sa.Column('creditor_id', sa.String(length=35), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("remittance_type IN ('sepa')", name='valid_remittance_type'),
    sa.CheckConstraint("status IN ('draft', 'ready', 'submitted', 'processed', 'closed', 'cancelled')", name='valid_remittance_status'),
    sa.CheckConstraint('total_amount >= 0', name='remittance_total_non_negative'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('remittance_number')
    )
    op.create_index('ix_remittances_emission_date', 'remittances', ['emission_date'], unique=False)
    op.create_index(op.f('ix_remittances_id'), 'remittances', ['id'], unique=False)
    op.create_index('ix_remittances_status', 'remittances', ['status'], unique=False)
    op.create_table('sepa_mandates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('mandate_reference', sa.String(length=35), nullable=False),
    sa.Column('creditor_id', sa.String(length=35), nullable=False),
    sa.Column('debtor_name', sa.String(length=255), nullable=False),
    sa.Column('debtor_iban', sa.String(length=34), nullable=False),
    sa.Column('debtor_bic', sa.String(length=11), nullable=True),
    sa.Column('mandate_type', sa.String(length=20), nullable=False),
    sa.Column('signature_method', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('signed_at', sa.Date(), nullable=False),
    sa.Column('document_path', sa.String(length=500), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("mandate_type IN ('recurrent', 'one_off')", name='valid_mandate_type'),
    sa.CheckConstraint("signature_method IN ('paper', 'digital')", name='valid_signature_method'),
    sa.CheckConstraint("status IN ('active', 'cancelled', 'expired')", name='valid_mandate_status'),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mandate_reference')
    )
    op.create_index(op.f('ix_sepa_mandates_id'), 'sepa_mandates', ['id'], unique=False)
    op.create_index('ix_sepa_mandates_member_id', 'sepa_mandates', ['member_id'], unique=False)
    op.create_index('ix_sepa_mandates_status', 'sepa_mandates', ['status'], unique=False)
    op.add_column('organization_settings', sa.Column('creditor_id', sa.String(length=35), nullable=True))
    op.add_column('organization_settings', sa.Column('sepa_format', sa.String(length=20), nullable=True))
    op.create_foreign_key('fk_receipts_remittance_id', 'receipts', 'remittances', ['remittance_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_receipts_remittance_id', 'receipts', type_='foreignkey')
    op.drop_column('organization_settings', 'sepa_format')
    op.drop_column('organization_settings', 'creditor_id')
    op.drop_index('ix_sepa_mandates_status', table_name='sepa_mandates')
    op.drop_index('ix_sepa_mandates_member_id', table_name='sepa_mandates')
    op.drop_index(op.f('ix_sepa_mandates_id'), table_name='sepa_mandates')
    op.drop_table('sepa_mandates')
    op.drop_index('ix_remittances_status', table_name='remittances')
    op.drop_index(op.f('ix_remittances_id'), table_name='remittances')
    op.drop_index('ix_remittances_emission_date', table_name='remittances')
    op.drop_table('remittances')
    op.drop_index(op.f('ix_payment_providers_id'), table_name='payment_providers')
    op.drop_table('payment_providers')
    # ### end Alembic commands ###
