"""add_bookings

Adds the Simple Bookings tables: ``spaces`` (bookable resources with daily
opening hours), ``space_slots`` (admin-defined slots on concrete dates with a
capacity; slots generated by one repeat rule share a ``series_id``), and
``bookings`` (a member holding a slot, booked or waitlisted). Capacity is
enforced in the service under a row lock; the partial unique index below only
stops a member holding two active rows for the same slot.

Revision ID: c5d6e7f8a9b0
Revises: 120971684ed2
Create Date: 2026-07-22 12:00:00.000000
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c5d6e7f8a9b0'
down_revision: Union[str, None] = '120971684ed2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        'spaces',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=200), nullable=False),
        sa.Column('space_type', sa.String(length=50), nullable=True),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('open_time', sa.Time(), nullable=False),
        sa.Column('close_time', sa.Time(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.CheckConstraint('close_time > open_time', name='space_hours_valid'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index('ix_spaces_active', 'spaces', ['is_active'], unique=False)

    op.create_table(
        'space_slots',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('space_id', sa.Integer(), nullable=False),
        sa.Column('slot_date', sa.Date(), nullable=False),
        sa.Column('start_time', sa.Time(), nullable=False),
        sa.Column('end_time', sa.Time(), nullable=False),
        sa.Column('capacity', sa.SmallInteger(), nullable=False, server_default='1'),
        sa.Column('series_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.CheckConstraint('end_time > start_time', name='space_slot_time_valid'),
        sa.CheckConstraint('capacity >= 1', name='space_slot_capacity_valid'),
        sa.ForeignKeyConstraint(['space_id'], ['spaces.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index('ix_space_slots_space_date', 'space_slots', ['space_id', 'slot_date'], unique=False)
    op.create_index('ix_space_slots_series', 'space_slots', ['series_id'], unique=False)

    op.create_table(
        'bookings',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('space_slot_id', sa.Integer(), nullable=False),
        sa.Column('member_id', sa.Integer(), nullable=False),
        sa.Column('status', sa.String(length=20), nullable=False, server_default='booked'),
        sa.Column('waitlisted_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('cancelled_by_user_id', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.CheckConstraint(
            "status IN ('booked', 'waitlisted', 'cancelled')",
            name='booking_status_valid',
        ),
        sa.ForeignKeyConstraint(['space_slot_id'], ['space_slots.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['cancelled_by_user_id'], ['users.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index('ix_bookings_slot', 'bookings', ['space_slot_id'], unique=False)
    op.create_index('ix_bookings_member', 'bookings', ['member_id'], unique=False)
    op.create_index(
        'uq_bookings_member_slot_active',
        'bookings',
        ['space_slot_id', 'member_id'],
        unique=True,
        postgresql_where=sa.text("status IN ('booked', 'waitlisted')"),
    )


def downgrade() -> None:
    op.drop_index('uq_bookings_member_slot_active', table_name='bookings')
    op.drop_index('ix_bookings_member', table_name='bookings')
    op.drop_index('ix_bookings_slot', table_name='bookings')
    op.drop_table('bookings')
    op.drop_index('ix_space_slots_series', table_name='space_slots')
    op.drop_index('ix_space_slots_space_date', table_name='space_slots')
    op.drop_table('space_slots')
    op.drop_index('ix_spaces_active', table_name='spaces')
    op.drop_table('spaces')
