"""add_payment_method_and_holder_to_persons

Revision ID: dba8415a3c7f
Revises: be824d96ca35
Create Date: 2026-04-09 05:35:36.040117
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dba8415a3c7f'
down_revision: Union[str, None] = 'be824d96ca35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('persons', sa.Column('bank_holder_name', sa.String(length=255), nullable=True))
    op.add_column('persons', sa.Column('payment_method', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('persons', 'payment_method')
    op.drop_column('persons', 'bank_holder_name')
    # ### end Alembic commands ###
