"""add groups table, group_id FK, restricted role

Revision ID: f993a3100855
Revises: 2ca72b2a038b
Create Date: 2026-03-17 21:04:07.467410
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f993a3100855'
down_revision: Union[str, None] = '2ca72b2a038b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_billable', sa.Boolean(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("slug ~ '^[a-z0-9-]+$'", name='group_slug_format'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('idx_groups_display_order', 'groups', ['display_order'], unique=False)
    op.create_index('idx_groups_slug', 'groups', ['slug'], unique=False)
    op.add_column('membership_types', sa.Column('group_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'membership_types', 'groups', ['group_id'], ['id'], ondelete='SET NULL')
    # Update role constraint to include 'restricted'
    op.drop_constraint('valid_role', 'users', type_='check')
    op.create_check_constraint('valid_role', 'users', "role IN ('super_admin', 'admin', 'restricted', 'member')")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'membership_types', type_='foreignkey')
    op.drop_column('membership_types', 'group_id')
    # Revert role constraint
    op.drop_constraint('valid_role', 'users', type_='check')
    op.create_check_constraint('valid_role', 'users', "role IN ('super_admin', 'admin', 'member')")
    op.drop_index('idx_groups_slug', table_name='groups')
    op.drop_index('idx_groups_display_order', table_name='groups')
    op.drop_table('groups')
    # ### end Alembic commands ###
