"""add_billing_runs_table

Revision ID: fe0fc0bd21e5
Revises: 98254e4ba28b
Create Date: 2026-06-09 09:10:45.085017
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fe0fc0bd21e5'
down_revision: Union[str, None] = '98254e4ba28b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billing_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('frequency', sa.String(length=20), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('triggered_by', sa.String(length=20), nullable=False),
    sa.Column('triggered_by_user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('receipts_generated', sa.Integer(), nullable=False),
    sa.Column('errors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("frequency IN ('monthly', 'quarterly', 'annual')", name='valid_billing_run_frequency'),
    sa.CheckConstraint("status IN ('success', 'failed', 'partial_failure')", name='valid_billing_run_status'),
    sa.CheckConstraint("triggered_by IN ('scheduled', 'manual')", name='valid_billing_run_triggered_by'),
    sa.ForeignKeyConstraint(['triggered_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('frequency', 'period_start', 'period_end', name='uq_billing_runs_frequency_period')
    )
    op.create_index(op.f('ix_billing_runs_id'), 'billing_runs', ['id'], unique=False)
    op.create_index('ix_billing_runs_triggered_started', 'billing_runs', ['triggered_by', 'started_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_billing_runs_triggered_started', table_name='billing_runs')
    op.drop_index(op.f('ix_billing_runs_id'), table_name='billing_runs')
    op.drop_table('billing_runs')
    # ### end Alembic commands ###
